{den, ...}: {
  den.hosts.x86_64-linux.lenovo-legion-16iah7h-PF3XJ8SP = {
    users.ayin = {
      includes = [
        den.batteries.primary-user
        (den.batteries.user-shell "zsh")
      ];
    };
  };

  den.aspects.lenovo-legion-16iah7h-PF3XJ8SP = {
    includes = [
      den.aspects.agenix
      den.aspects.bichannel
      den.aspects.battery
      den.aspects.system-settings
      den.aspects.bluetooth
      den.aspects.bluetuith
      den.aspects.cachyos-kernel
      den.aspects.cava
      den.aspects.cliphist
      den.aspects.dev
      den.aspects.fastfetch
      den.aspects.fcitx5
      den.aspects.firefox
      den.aspects.foot
      den.aspects.gc
      den.aspects.greetd
      den.aspects.gtklock
      den.aspects.helix
      den.aspects.imv
      den.aspects.kanshi
      den.aspects.lenovo-legion
      den.aspects.lix
      den.aspects.mpv
      den.aspects.nh
      den.aspects.nur
      den.aspects.openssh
      den.aspects.pear-desktop
      den.aspects.pipewire
      den.aspects.steam
      den.aspects.stylix
      den.aspects.sway
      den.aspects.taskwarrior
      den.aspects.tofi
      den.aspects.vesktop
      den.aspects.waybar
      den.aspects.waydroid
      den.aspects.yazi
      den.aspects.zalo
      den.aspects.zathura
      den.aspects.zed-editor
      den.aspects.zsh
      den.aspects.nodejs
      den.aspects.p7zip
      den.aspects.cmake
      den.aspects.deno
      den.aspects.docker
      den.aspects.ffmpeg
      den.aspects.gallery-dl
      den.aspects.gcc
      den.aspects.git-xet
      den.aspects.go
      den.aspects.gradle
      den.aspects.itch
      den.aspects.llama
      den.aspects.llvm
      den.aspects.miktex
      den.aspects.mingw
      den.aspects.notion
      den.aspects.obs-studio
      den.aspects.ollama
      den.aspects.opencode
      den.aspects.openjdk
      den.aspects.pandoc
      den.aspects.poetry
      den.aspects.protobuf
      den.aspects.protonvpn
      den.aspects.python
      den.aspects.rufus
      den.aspects.telegram
      den.aspects.virtualbox
      den.aspects.vivaldi
      den.aspects.vortex
      den.aspects.webtorrent
      den.aspects.xmake
      den.aspects.yt-dlp
      den.aspects.Hyprland
      den.aspects.Noctalia-shell
      den.aspects.wezterm
    ];
  };
}
