[audio]
enable_overdrive = true

[bar.default]
background_opacity = 0.79999998211860657
border_width = 1.0
capsule = true
layer = "overlay"
margin_ends = 16
margin_opposite_edge = 10
panel_overlap = 0
position = "left"
shadow = false

[calendar]
enabled = true

[desktop_widgets]
enabled = false

[idle]
pre_action_fade_seconds = 0

[location]
auto_locate = true

[lockscreen]
wallpaper = "/home/ayin/projs/nixconf/assets/wallpapers/girls-last-tour-library.jpg"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1481.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[notification]
layer = "overlay"

[shell]
avatar_path = "/home/ayin/projs/nixconf/assets/wallpapers/avatars/default.png"
font_family = "Inter"
polkit_agent = true
settings_show_advanced = true
ui_scale = 1.2500000111758709

    [shell.shadow]
    direction = "center"

[system.monitor]
cpu_poll_seconds = 4
disk_poll_seconds = 4
gpu_poll_seconds = 4
memory_poll_seconds = 4
network_poll_seconds = 4

[theme]
builtin = "Gruvbox"
community_palette = "Monochrome"

    [theme.templates]
    builtin_ids = [ "cava", "helix", "kitty", "mango" ]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper.automation]
recursive = false

[weather]
refresh_minutes = 5
