{den, ...}: {
  den.aspects.lenovo-legion-16iah7h-PF3XJ8SP.provides.to-users = {user, ...}: {
    nixos =
      # Do not modify this file!  It was generated by ‘nixos-generate-config’
      # and may be overwritten by future invocations.  Please make changes
      # to /etc/nixos/configuration.nix instead.
      {
        config,
        lib,
        pkgs,
        modulesPath,
        ...
      }: {
        imports = [
          (modulesPath + "/installer/scan/not-detected.nix")
        ];

        boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod"];
        boot.initrd.kernelModules = [];
        boot.kernelModules = ["kvm-intel"];
        boot.extraModulePackages = [];

        fileSystems."/" = {
          device = "/dev/disk/by-uuid/c4439d0c-7d2f-4afd-9699-63f9cb617dba";
          fsType = "btrfs";
        };

        fileSystems."/home" = {
          device = "/dev/disk/by-uuid/c4439d0c-7d2f-4afd-9699-63f9cb617dba";
          fsType = "btrfs";
          options = ["subvol=home"];
        };

        fileSystems."/nix" = {
          device = "/dev/disk/by-uuid/c4439d0c-7d2f-4afd-9699-63f9cb617dba";
          fsType = "btrfs";
          options = ["subvol=nix"];
        };

        fileSystems."/boot" = {
          device = "/dev/disk/by-uuid/73AB-E434";
          fsType = "vfat";
          options = ["fmask=0077" "dmask=0077"];
        };

        swapDevices = [
          {device = "/dev/disk/by-uuid/0200c342-a217-4b28-8856-19363cc97974";}
        ];

        nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
        hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };
  };
}
