#include <X11/XF86keysym.h>
/* DELL dwm config — generated by home-manager
 * (modules/features/desktop/compositors/dwm/default.nix, 2026-09-23).
 * Derived from upstream dwm 6.6 config.def.h; colors are the stylix
 * kanagawa-dragon palette. Keybinds mirror the legion mango setup where
 * dwm's action set allows (same MODKEY=Mod4, W-Return terminal,
 * W-d launcher, W-b browser, W-Ctrl-l lock, W-Shift-s screenshot,
 * W-q kill, W-Shift-f fullscreen, 1..9 tags + Shift-1..9 send).
 * Mango knobs with no dwm equivalent (blur, animations, scroller
 * layouts, gapp*) are dropped — dwm is a minimal dwm-style tiler.
 */

/* appearance */
static const unsigned int borderpx  = 0;        /* mango borderpx = 0 */
static const unsigned int snap      = 32;       /* snap pixel */
static const int showbar            = 1;        /* dwm's native bar */
static const int topbar             = 1;
static const char *fonts[]          = { "Maple Mono NF CN:size=10" };
static const char dmenufont[]       = "Maple Mono NF CN:size=10";
static const char col_bg[]          = "#181616";  /* base00 */
static const char col_bg2[]         = "#223249";  /* base01 */
static const char col_fg[]          = "#c5c9c5";  /* base05 */
static const char col_fg_dim[]      = "#8ba4b0";  /* base04 */
static const char col_sel[]         = "#8ba4b0";  /* base0D */
static const char *colors[][3]      = {
	/*               fg         bg         border   */
	[SchemeNorm] = { col_fg, col_bg, col_bg2 },
	[SchemeSel]  = { col_bg, col_sel, col_sel },
};

/* tagging */
static const char *tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };

static const Rule rules[] = {
	/* class      instance    title       tags mask     isfloating   monitor */
	{ "Gimp",     NULL,       NULL,       0,            1,           -1 },
	{ "Pavucontrol", NULL,    NULL,       0,            1,           -1 },
	{ "Arandr",   NULL,       NULL,       0,            1,           -1 },
	{ "pcmanfm",  NULL,       NULL,       0,            1,           -1 },
};

/* layout(s) */
static const float mfact     = 0.55;
static const int nmaster     = 1;
static const int resizehints = 1;
static const int lockfullscreen = 1;

static const Layout layouts[] = {
	/* symbol     arrange function */
	{ "[]=",      tile },
	{ "><>",      NULL },
	{ "[M]",      monocle },
};

/* key definitions */
#define MODKEY Mod4Mask   /* mango SUPER parity */
#define TAGKEYS(KEY,TAG) \
	{ MODKEY,                       KEY,      view,           {.ui = 1 << TAG} }, \
	{ MODKEY|ControlMask,           KEY,      toggleview,     {.ui = 1 << TAG} }, \
	{ MODKEY|ShiftMask,             KEY,      tag,            {.ui = 1 << TAG} }, \
	{ MODKEY|ControlMask|ShiftMask, KEY,      toggletag,      {.ui = 1 << TAG} },

/* helper for spawning shell commands in the pre dwm-5.0 fashion */
#define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }

/* commands */
static char dmenumon[2] = "0";
static const char *dmenucmd[] = { "dmenu_run", "-m", dmenumon, "-fn", dmenufont, "-nb", col_bg, "-nf", col_fg, "-sb", col_sel, "-sf", col_bg, NULL };
static const char *termcmd[]  = { "st", NULL };
static const char *browsercmd[]  = { "falkon", NULL };
static const char *lockcmd[]  = { "i3lock", "-n", "-c", "181616", NULL };
static const char *shotcmd[]  = { "scrot", NULL };
static const char *volupcmd[] = { "wpctl", "set-volume", "-l", "1.0", "@DEFAULT_AUDIO_SINK@", "5%+", NULL };
static const char *voldncmd[] = { "wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%-", NULL };
static const char *volmutecmd[] = { "wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle", NULL };
static const char *brupcmd[] = { "brightnessctl", "set", "+5%", NULL };
static const char *brdncmd[] = { "brightnessctl", "set", "5%-", NULL };

static const Key keys[] = {
	/* modifier                     key        function        argument */
	{ MODKEY,                       XK_Return, spawn,          {.v = termcmd } },
	{ MODKEY,                       XK_d,      spawn,          {.v = dmenucmd } },
	{ MODKEY|ShiftMask,             XK_b,      spawn,          {.v = browsercmd } },
	{ MODKEY|ControlMask,           XK_l,      spawn,          {.v = lockcmd } },
	{ MODKEY|ShiftMask,             XK_s,      spawn,          {.v = shotcmd } },

	/* window management (mango parity) */
	{ MODKEY,                       XK_q,      killclient,     {0} },
	{ MODKEY,                       XK_f,      togglefullscreen, {0} },
	{ MODKEY,                       XK_j,      focusstack,     {.i = +1 } },
	{ MODKEY,                       XK_k,      focusstack,     {.i = -1 } },
	{ MODKEY|ShiftMask,             XK_h,      movestack,      {.i = -1 } },
	{ MODKEY|ShiftMask,             XK_l,      movestack,      {.i = +1 } },
	{ MODKEY,                       XK_h,      setmfact,       {.f = -0.05} },
	{ MODKEY|ShiftMask,             XK_e,      quit,           {0} },
	{ MODKEY,                       XK_Tab,    view,           {0} },

	/* per-tag focus / send (mango SUPER,N / SUPER+SHIFT,N) */
	TAGKEYS(                        XK_1,                      0)
	TAGKEYS(                        XK_2,                      1)
	TAGKEYS(                        XK_3,                      2)
	TAGKEYS(                        XK_4,                      3)
	TAGKEYS(                        XK_5,                      4)
	TAGKEYS(                        XK_6,                      5)
	TAGKEYS(                        XK_7,                      6)
	TAGKEYS(                        XK_8,                      7)
	TAGKEYS(                        XK_9,                      8)

	/* media keys (mango bindl XF86*) */
	{ 0,                            XF86XK_AudioRaiseVolume, spawn, {.v = volupcmd } },
	{ 0,                            XF86XK_AudioLowerVolume, spawn, {.v = voldncmd } },
	{ 0,                            XF86XK_AudioMute,        spawn, {.v = volmutecmd } },
	{ 0,                            XF86XK_MonBrightnessUp,  spawn, {.v = brupcmd } },
	{ 0,                            XF86XK_MonBrightnessDown,spawn, {.v = brdncmd } },
};

/* button definitions */
static const Button buttons[] = {
	{ ClkLtSymbol,          0,              Button1,        setlayout,      {0} },
	{ ClkLtSymbol,          0,              Button3,        setlayout,      {.v = &layouts[2]} },
	{ ClkWinTitle,          0,              Button2,        zoom,           {0} },
	{ ClkStatusText,        0,              Button2,        spawn,          {.v = termcmd } },
	{ ClkClientWin,         MODKEY,         Button1,        movemouse,      {0} },
	{ ClkClientWin,         MODKEY,         Button2,        togglefloating, {0} },
	{ ClkClientWin,         MODKEY,         Button3,        resizemouse,    {0} },
	{ ClkTagBar,            0,              Button1,        view,           {0} },
	{ ClkTagBar,            0,              Button3,        toggleview,     {0} },
	{ ClkTagBar,            MODKEY,         Button1,        tag,            {0} },
	{ ClkTagBar,            MODKEY,         Button3,        toggletag,      {0} },
};
